version: "2"
services:
  bus:
    build:
      context: ./bus
      dockerfile: bus.dockerfile
    ports:
      - 8081:8080

  news:
    build:
      context: ./news
      dockerfile: news.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongonews
    links: 
      - mongonews

  mongonews:
    image: mongo
    restart: always
    volumes: 
      - database:/data/db
    container_name: 'mongonews'
  mongoperson:
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb
    container_name: 'mongoperson'

  person-service:
    container_name: personen-service
    build:
      context: ./person
      dockerfile: person.dockerfile
    image: personen-service
    ports:
      - 3000:3000
    depends_on:
      - mongoperson
    links:
      - mongoperson
  mensa-service:
    container_name: mensa-service
    build:
      context: ./mensa
      dockerfile: mensa.dockerfile
    image: mensa-service
    ports:
      - 5000:5000
  greeter-service:
    container_name: greeter-service
    build:
      context: ./greeter
      dockerfile: greeter.dockerfile
    image: greeter-service
    ports:
     - 5001:5000

volumes:
  database: {}
  db-data:
  db-config: