version: "2"
services:
  bus:
    build:
      context: ./bus
      dockerfile: bus.dockerfile
    networks: [microservices]
    ports:
      - 8081:8080
    container_name: 'bus'

  news:
    build:
      context: ./news
      dockerfile: news.dockerfile
    networks: [microservices]
    ports:
      - 8080:8080
    depends_on:
      - mongonews
    links:
      - mongonews
    container_name: 'news'

  mongonews:
    image: mongo
    networks: [microservices]
    restart: always
    volumes:
      - database:/data/db
    container_name: 'mongonews'
  mongoperson:
    image: mongo
    networks: [microservices]
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb
    container_name: 'mongoperson'
  mysql:
    image: mysql
    restart: always
    networks: [microservices]
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: db123!
      MYSQL_DATABASE: places
  orte:
    build:
      context: ./orte
      dockerfile: orte.dockerfile
    networks: [microservices]
    ports:
      - 4000:8080
    links:
      - mysql
  person-service:
    container_name: personen-service
    build:
      context: ./person
      dockerfile: person.dockerfile
    image: personen-service
    networks: [microservices]
    ports:
      - 3000:3000
    depends_on:
      - mongoperson
    links:
      - mongoperson
    container_name: 'person'
  mensa-service:
    container_name: mensa-service
    build:
      context: ./mensa
      dockerfile: mensa.dockerfile
    image: mensa-service
    networks: [microservices]
    ports:
      - 5000:5000
    container_name: 'mensa'
  greeter-service:
    container_name: greeter-service
    build:
      context: ./greeter
      dockerfile: greeter.dockerfile
    image: greeter-service
    networks: [microservices]
    ports:
     - 5001:5000
    container_name: 'greeter'
  frontend-service:
    container_name: frontend-service
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    image: frontend-service
    networks: [microservices]
    ports:
     - 5002:5000
    container_name: 'frontend'

volumes:
  database: {}
  db-data:
  db-config:
  mysql-data:

networks:
  microservices:
    driver: bridge
