
version: "3"
services:
  bus:
    image: tomk3n/bus-ms
    ports:
      - 8081:8080
    
  news:
    image: tomk3n/newsletter-ms
    ports:
      - 8080:8080
    depends_on:
      - mongonews
    links:
      - mongonews

  mongonews:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
     
  mongoperson:
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb

  mysql:
    image: mariadb
    # restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db123!
      MYSQL_DATABASE: places

  orte:
    image: tomk3n/ortemock
    ports:
      - 3001:3000
    links:
      - mysql
    
  person:
    image: tomk3n/sa_personen_service
    ports:
      - 3000:3000
    depends_on:
      - mongoperson
    links:
      - mongoperson

  mensa:
    image: tomk3n/short-mensa-service
    ports:
      - 5000:5000

  greeter:
    image: tomk3n/short-greeter-service
    ports:
     - 5001:5000

  frontend-service:
    image: tomk3n/short-frontend-service
    ports:
     - 80:5000

volumes:
  database: {}
  db-data:
  db-config:
  mysql-data:

