version: "2"
services:
  bus:
    build:
      context: ./bus
      dockerfile: bus.dockerfile
    ports:
      - 8081:8080

  news:
    build:
      context: ./news
      dockerfile: news.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongonews
    links: 
      - mongonews

  mongonews:
    image: mongo
    restart: always
    volumes: 
      - database:/data/db
    container_name: 'mongonews'
  mongoperson:
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb
    container_name: 'mongoperson'

  person:
    build:
      context: ./person
      dockerfile: person.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongoperson
    links:
      - mongoperson

      
volumes:
  database: {}
  db-data:
  db-config: